Algoritmo "semnome"

Var

mtrz : vetor [1..4,1..5] de inteiro
l,c : inteiro

Inicio

para l de 1 ate 4 passo 1 faca
   para c de 1 ate 5 passo 1 faca
       escreval (" digite um numero na posição [", l, "," , c, "]:")
       leia (mtrz[l,c])
   fimpara
fimpara


para l de 1 ate 4 passo 1 faca
   para c de 1 ate 5 passo 1 faca
        escreval ("matriz digitada", mtrz[l,c] )
   fimpara
fimpara


Fimalgoritmo